name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  export-web:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot
        uses: firebelley/godot-export@v3.1.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.6/Godot_v4.6-stable_linux.x86_64.zip
          relative_project_path: .
          archive_export_output: false

      - name: Web Build
        run: |
          mkdir -p web_build
          godot --headless --export-release "Web" web_build/index.html
          echo "Export completed. Checking output..."
          ls -la web_build/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: web_build