name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  export-web:
    runs-on: ubuntu-24.04
    container: barichello/godot-ci:4.6
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download Export Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          wget -q https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_export_templates.tpz
          unzip -q Godot_v4.6-stable_export_templates.tpz -d ~/.local/share/godot/export_templates
          mv ~/.local/share/godot/export_templates/templates ~/.local/share/godot/export_templates/4.6.stable
          rm Godot_v4.6-stable_export_templates.tpz

      - name: Web Build
        run: |
          mkdir -v -p web_build
          godot --headless --export-release "Web" web_build/index.html
          echo "Export completed. Checking output..."
          ls -la web_build/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: web_build
